-- Config for Instances
InstanceData = {
    Firelands = {
        order = 3.01,
        displayName = "Firelands",
        zoneId = {198, 12},
        instanceId = 720,
        category = "raid",
        difficultyId = 14,
        description = "Firelands (normal/heroic) [Alysrazor + Ragnaros]",
    },
    Ulduar = {
        order = 3.02,
        displayName = "Ulduar",
        zoneId = {120},
        instanceId = 603,
        category = "raid",
        difficultyId = 14,
        description = "Ulduar (normal) [Yogg-Saron]",
    },
    Antorus = {
        order = 3.03,
        displayName = "Antorus",
        zoneId = {885},
        instanceId = 1712,
        category = "raid",
        difficultyId = 14,
        description = "Antorus The Burning Throne (normal/heroic) [F'harg]",
    },
    TombofSargeras = {
        order = 3.04,
        displayName = "Tomb of Sargeras",
        instanceId = 1676,
        zoneId = {646},
        category = "raid",
        difficultyId = 14,
        description = "Tomb of Sargeras, (normal/heroic) [Mistress Sassz'ine]",
    },
    Nighthold = {
        order = 3.05,
        displayName = "Nighthold",
        zoneId = {680},
        instanceId = 1530,
        category = "raid",
        difficultyId = 14,
        description = "Nighthold Citadel (normal/heroic) [Gul'dan]",
    },
    SanctumOfDomination = {
        order = 3.06,
        displayName = "Sanctum of Domination",
        zoneId = {1543},
        instanceId = 2450,
        category = "raid",
        difficultyId = 14,
        description = "Sanctum of Domination (normal/heroic) [The Nine]",
    },
    SepulcherOfTheFirstOnes = {
        order = 3.07,
        displayName = "Sepulcher of the First Ones",
        zoneId = {1970},
        instanceId = 2481,
        category = "raid",
        difficultyId = 14,
        description = "Sepulcher of the First Ones (normal/heroic) [Lihuvim]",
    },
    VaultOfTheIncarnates = {
        order = 3.08,
        displayName = "Vault of the Incarnates",
        zoneId = {2025},
        instanceId = 2522,
        category = "raid",
        difficultyId = 14,
        description = "Vault of the Incarnates (normal/heroic) [Dathea / Terros]",
    },
    NerubarPalace = {
        order = 3.09,
        displayName = "Nerub-ar Palace",
        zoneId = {2213},
        instanceId = 2657,
        category = "raid",
        difficultyId = 14,
        description = "Nerub-ar Palace (normal/heroic) [Queen Ansurek]",
    },
    LiberationOfUndermine = {
        order = 3.10,
        displayName = "Liberation of Undermine",
        zoneId = {15347},
        instanceId = 2769,
        category = "raid",
        difficultyId = 14,
        description = "Liberation of Undermine (normal/heroic) [Gallywix]",
    },
    ReturnToKarazhan = {
        order = 4.1,
        displayName = "Return to Karazhan",
        zoneId = {42, 13},
        instanceId = 1651,
        category = "dungeon",
        difficultyId = 23,
        description = "Return to Karazhan (mythic) [Attumen the Huntsman]",
    },
    OperationMechagon = {
        order = 4.2,
        displayName = "Operation: Mechagon",
        zoneId = {1462},
        instanceId = 2097,
        category = "dungeon",
        difficultyId = 23,
        description = "Operation: Mechagon (mythic) [HK-8 Aerial]",
    },
    TazaeshTheVeiledMarket = {
        order = 4.3,
        displayName = "Tazavesh: The Veiled Market",
        zoneId = {1550, 2016},
        instanceId = 2441,
        category = "dungeon",
        difficultyId = 23,
        description = "Tazavesh (mythic) [Soleah]",
    },
    DawnOfTheInfinite = {
        order = 4.4,
        displayName = "Dawn of the Infinite",
        zoneId = {2025},
        instanceId = 2579,
        category = "dungeon",
        difficultyId = 23,
        description = "Dawn of the Infinite (mythic) [Deios]",
    },
    IcecrownCitadel = {
        order = 5.1,
        displayName = "Icecrown Citadel",
        zoneId = {118},
        instanceId = 631,
        category = "raid",
        difficultyId = 4,
        description = "Icecrown Citadel (heroic) [Lich King]",
        factionSpecific = true,
    },
    JourneyToTheTimelessIsle = {
        order = 5.2,
        displayName = "Journey to the Timeless Isle",
        zoneId = {0},
        instanceId = nil,
        category = "transmogsAndPets",
        difficultyId = nil,
        description = "33231, 33232",
        factionSpecific = true,
    },
    BattleForDazarAlor = {
        order = 5.3,
        displayName = "Battle for Dazar'Alor",
        zoneId = {1161, 1165},
        instanceId = 2070,
        category = "raid",
        difficultyId = 14,
        description = "Battle for Dazar'Alor (normal/heroic) [High Tinker Mekkatorque]",
        factionSpecific = true,
    },
    BlackTemple = {
        order = 6.1,
        displayName = "Black Temple",
        zoneId = {104},
        instanceId = 564,
        category = "transmogsAndPets",
        difficultyId = 14,
        description = "Black Temple (normal) [Illidan Stormrage]",
    },
    LostInTheDeepDaily = {
        order = 6.2,
        displayName = "Lost in the Deep Daily",
        zoneId = {207},
        instanceId = nil,
        category = "transmogsAndPets",
        difficultyId = nil,
        description = "26710",
    },
    SiegeOfOrgrimmar = {
        order = 6.3,
        displayName = "Siege of Orgrimmar",
        zoneId = {390, 1530},
        instanceId = 1136,
        category = "transmogsAndPets",
        difficultyId = 14,
        description = "Siege of Orgrimmar, 10 (heroic) [Garrosh Hellscream] / (normal) [Kor'kron Dark Shaman]",
    },
    EmeraldNightmare = {
        order = 6.4,
        displayName = "Emerald Nightmare",
        zoneId = {641},
        instanceId = 1520,
        category = "transmogsAndPets",
        difficultyId = 15,
        description = "Emerald Nightmare (heroic) [Xavius]",
    },
    TheEternalPalace = {
        order = 6.5,
        displayName = "The Eternal Palace",
        zoneId = {1355, 1528},
        instanceId = 2164,
        category = "transmogsAndPets",
        difficultyId = 15,
        description = "The Eternal Palace (heroic) [Za'qul]",
    },
    CastleNathria = {
        order = 6.6,
        displayName = "Castle Nathria (normal/heroic) [Sire Denathrius]",
        zoneId = {1525},
        instanceId = 2296,
        category = "transmogsAndPets",
        difficultyId = 14,
        description = "Castle Nathria",
    },
    AberrusTheShadowedCrucible = {
        order = 6.7,
        displayName = "Aberrus, the shadowed Crucible (normal/heroic) [Sire Denathrius]",
        zoneId = {2133},
        instanceId = 2569,
        category = "transmogsAndPets",
        difficultyId = 14,
        description = "Aberrus, the Shadowed Crucible (normal/heroic) [Scalecommander Sarkareth]",
    },
    AmirdrassilTheDreamsHope = {
        order = 6.8,
        displayName = "Amirdrassil, the Dream's Hope (normal/heroic) [Sire Denathrius]",
        zoneId = {2200},
        instanceId = 2549,
        category = "transmogsAndPets",
        difficultyId = 15,
        description = "Amirdrassil, the Dream's Hope (normal/heroic) [Fyrakk]",
    }
}