-- Config for Instances
InstanceData = {
    Firelands = {
        order = 3.01,
        displayName = "Firelands",
        zoneId = {198, 12},
        category = "raid",
        difficultyId = 14,
        description = "Firelands (normal/heroic) [Alysrazor + Ragnaros]",
    },
    Ulduar = {
        order = 3.02,
        displayName = "Ulduar",
        zoneId = {120},
        category = "raid",
        difficultyId = 14,
        description = "Ulduar (normal) [Yogg-Saron]",
    },
    Antorus = {
        order = 3.03,
        displayName = "Antorus",
        zoneId = {885},
        category = "raid",
        difficultyId = 14,
        description = "Antorus The Burning Throne (normal/heroic) [F'harg]",
    },
    TombofSargeras = {
        order = 3.04,
        displayName = "Tomb of Sargeras",
        zoneId = {646},
        category = "raid",
        difficultyId = 14,
        description = "Tomb of Sargeras, (normal/heroic) [Mistress Sassz'ine]",
    },
    Nighthold = {
        order = 3.05,
        displayName = "Nighthold",
        zoneId = {680},
        category = "raid",
        difficultyId = 14,
        description = "Nighthold Citadel (normal/heroic) [Gul'dan]",
    },
    SanctumOfDomination = {
        order = 3.06,
        displayName = "Sanctum of Domination",
        zoneId = {1543},
        category = "raid",
        difficultyId = 14,
        description = "Sanctum of Domination (normal/heroic) [The Nine]",
    },
    SepulcherOfTheFirstOnes = {
        order = 3.07,
        displayName = "Sepulcher of the First Ones",
        zoneId = {1970},
        category = "raid",
        difficultyId = 14,
        description = "Sepulcher of the First Ones (normal/heroic) [Lihuvim]",
    },
    VaultOfTheIncarnates = {
        order = 3.08,
        displayName = "Vault of the Incarnates",
        zoneId = {2025},
        category = "raid",
        difficultyId = 14,
        description = "Vault of the Incarnates (normal/heroic) [Dathea / Terros]",
    },
    NerubarPalace = {
        order = 3.09,
        displayName = "Nerub-ar Palace",
        zoneId = {2213},
        category = "raid",
        difficultyId = 14,
        description = "Nerub-ar Palace (Normal) : Queen Ansurek (Sureki Skyrazor)",
    },
    LiberationOfUndermine = {
        order = 3.10,
        displayName = "Liberation of Undermine",
        zoneId = {}, -- keine Zone definiert, ggf. ergänzen
        category = "raid",
        difficultyId = 14,
        description = "",
    },
    ReturnToKarazhan = {
        order = 4.1,
        displayName = "Return to Karazhan",
        zoneId = {42, 13},
        category = "dungeon",
        difficultyId = 23,
        description = "Return to Karazhan (mythic) [Attumen the Huntsman]",
    },
    OperationMechagon = {
        order = 4.2,
        displayName = "Operation: Mechagon",
        zoneId = {1462},
        category = "dungeon",
        difficultyId = 23,
        description = "Operation: Mechagon (mythic) [HK-8 Aerial]",
    },
    TazaeshTheVeiledMarket = {
        order = 4.3,
        displayName = "Tazavesh: The Veiled Market",
        zoneId = {1550, 2016},
        category = "dungeon",
        difficultyId = 23,
        description = "Tazavesh (mythic) [Soleah]",
    },
    DawnOfTheInfinite = {
        order = 4.4,
        displayName = "Dawn of the Infinite",
        zoneId = {2025},
        category = "dungeon",
        difficultyId = 23,
        description = "Dawn of the Infinite (mythic) [Deios]",
    },
    IcecrownCitadel = {
        order = 5.1,
        displayName = "Icecrown Citadel",
        zoneId = {118},
        category = "raid",
        difficultyId = 4,
        description = "Icecrown Citadel (heroic) [Lich King]",
        factionSpecific = true, -- prüfe Fraktion
    },
    JournesToTheTimelessIsle = {
        order = 5.2,
        displayName = "Journes to the Timeless Isle",
        zoneId = {}, -- keine Zone definiert
        category = "none",
        difficultyId = nil,
        description = "",
    },
    BattleForDazarAlor = {
        order = 5.3,
        displayName = "Battle for Dazar'Alor",
        zoneId = {1161, 1165},
        category = "raid",
        difficultyId = 14,
        description = "Battle for Dazar'Alor (normal/heroic) [High Tinker Mekkatorque]",
        factionSpecific = true,
    },
    BlackTemple = {
        order = 6.1,
        displayName = "Black Temple",
        zoneId = {104},
        category = "transmogsAndPets",
        difficultyId = nil,
        description = "Black Temple (normal) [Illidan Stormrage]",
    },
    LostInTheDeepDaily = {
        order = 6.2,
        displayName = "Lost in the Deep Daily",
        zoneId = {}, -- keine Zone definiert
        category = "transmogsAndPets",
        difficultyId = nil,
        description = "",
    },
    SiegeOfOrgrimmar = {
        order = 6.3,
        displayName = "Siege of Orgrimmar",
        zoneId = {390, 1530},
        category = "transmogsAndPets",
        difficultyId = 15,
        description = "Siege of Orgrimmar, 10 (heroic) [Garrosh Hellscream] / (normal) [Kor'kron Dark Shaman]",
    },
    EmeraldNightmare = {
        order = 6.4,
        displayName = "Emerald Nightmare",
        zoneId = {641},
        category = "transmogsAndPets",
        difficultyId = 15,
        description = "Emerald Nightmare (heroic) [Xavius]",
    },
    TheEternalPalace = {
        order = 6.5,
        displayName = "The Eternal Palace",
        zoneId = {1355, 1528},
        category = "transmogsAndPets",
        difficultyId = 15,
        description = "The Eternal Palace",
    },
    CastleNathria = {
        order = 6.6,
        displayName = "Castle Nathria",
        zoneId = {1525},
        category = "transmogsAndPets",
        difficultyId = 14,
        description = "Castle Nathria",
    },
    AberrusTheShadowedCrucible = {
        order = 6.7,
        displayName = "Aberrus, the shadowed Crucible",
        zoneId = {2133},
        category = "transmogsAndPets",
        difficultyId = 14,
        description = "Aberrus, the Shadowed Crucible :  Embodiment of the Hellforged",
    },
    AmirdrassilTheDreamsHope = {
        order = 6.8,
        displayName = "Amirdrassil, the Dream's Hope",
        zoneId = {2200},
        category = "transmogsAndPets",
        difficultyId = 15,
        description = "Amirdrassil, the Dream's Hope (Heroic) : Fyrakk (Embodiment of the Blazing)",
    }
}